<?php
/** @var string $csrfToken */
/** @var ?string $archiveToken */
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Batch TXT-to-SRT</title><link rel="stylesheet" href="/assets/tokens.css"><link rel="stylesheet" href="/assets/app.css"><link rel="stylesheet" href="/assets/batch.css"></head><body><main class="site-main"><div class="container"><section class="workspace-card"><p class="eyebrow">Batch conversion</p><h1>Convert multiple TXT files</h1><?php if (!isset($result)) :
    ?><form method="post" action="/batch/convert" enctype="multipart/form-data"><input type="hidden" name="_csrf" value="<?= htmlspecialchars($csrfToken, ENT_QUOTES, 'UTF-8') ?>"><?php require __DIR__ . '/components/drop-zone.php'; ?><label><input type="checkbox" name="repair" value="1"> Safe repair mode</label><button type="submit">Convert batch</button></form><?php
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  else :
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ?><?php require __DIR__ . '/components/batch-summary.php'; ?><?php require __DIR__ . '/components/file-list.php'; ?><?php if ($archiveToken !== null) :
    ?><a class="button-link" href="/batch/archive?token=<?= $archiveToken ?>">Download successful files as ZIP</a><?php
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        endif ?><p><a href="/batch">Convert another batch</a></p><?php
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  endif ?></section></div></main><script src="/assets/batch-upload.js" defer></script></body></html>
